version: '3'

services:
  postgres:
    ports:
      - 5432:5432

  adminer:
    ports:
      - 8080:8080

  dbeaver:
    ports:
      - 8081:8978

  redis:
    ports:
      - 6379:6379

  web:
    ports:
      - 3000:3000
