version: '3.8'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-blog}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-default}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

  redis:
    image: redis:latest
    
  
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=dracula
      - ADMINER_DEFAULT_SERVER=postgres
  
  dbeaver:
    image: dbeaver/cloudbeaver:latest

  web:
    build: .
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  db-data:
